name: Latest blog post workflow--1
on:
  schedule:
    # Runs every 55 minutes
    - cron: '*/55 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/rakibhasan455"
